tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "romkatv/powerlevel10k"
brew "exa"
brew "fzf"
brew "gh"
brew "hyperfine"
brew "lazygit"
brew "lua-language-server"
brew "neovim", args: ["HEAD"]
brew "stylua"
brew "zk"
brew "romkatv/powerlevel10k/powerlevel10k"
cask "iterm2"
