tap "cmacrae/formulae"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "jesseduffield/lazygit"
tap "koekeishiya/formulae"
brew "arp-scan"
brew "python@3.9"
brew "fzf"
brew "gcc"
brew "gh"
brew "htop"
brew "jq"
brew "lua"
brew "luajit", args: ["HEAD"]
brew "neovim", args: ["HEAD"]
brew "pandoc"
brew "python@3.8"
brew "ripgrep"
brew "stylua"
brew "tree"
brew "watch"
brew "jesseduffield/lazygit/lazygit"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai", args: ["HEAD"]
