#!/usr/bin/env zsh
# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# bsp or float (default: bsp)
yabai -m config layout bsp

# Set all padding and gaps to 20pt (default: 0)
yabai -m config top_padding    15
yabai -m config bottom_padding 15
yabai -m config left_padding   15
yabai -m config right_padding  15
yabai -m config window_gap     7

# set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier fn

# set modifier + left-click drag to resize window (default: move)
yabai -m config mouse_action1 move

# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize

# set focus follows mouse mode (default: off, options: off, autoraise, autofocus)
yabai -m config focus_follows_mouse autofocus

# floating windows are always on top (default: off)
yabai -m config window_topmost on

# window opacity (default: off)
# example: render all unfocused windows with 90% opacity
yabai -m config window_opacity off
yabai -m config active_window_opacity 0.95
yabai -m config normal_window_opacity 0.95

# Space Mapper
setup_space() {
  local idx="$1"
  local name="$2"
  local space=
  echo "setup space $idx : $name"

  space=$(yabai -m query --spaces --space "$idx")
  if [ -z "$space" ]; then
    yabai -m space --create
  fi

  yabai -m space "$idx" --label "$name"
  if [ "$idx" -lt "4" ]; then
    yabai -m space "$idx" --display 2
  else
    yabai -m space "$idx" --display 1
  fi
}

# Setup or destroy spaces as needed to match 9
for _ in $(yabai -m query --spaces | jq '.[].index | select(. > 4)'); do
  yabai -m space --destroy 5
done

# Desktop labels
setup_space 1 1_code
setup_space 2 2_web
setup_space 3 3_work
setup_space 4 4_misc

# Move spaces to correct displays
yabai -m space 1_code --display 2
yabai -m space 2_web --display 2
yabai -m space 3_work --display 2
yabai -m space 4_misc --display 1

# Window rules: manage off
yabai -m rule --add app=Finder manage=off
yabai -m rule --add app="^Préférences Système$" manage=off
yabai -m rule --add app="Stats" manage=off
yabai -m rule --add app="Steam" manage=off
yabai -m rule --add app="luajit" manage=off
yabai -m rule --add app="ChatGPT" manage=off

# Window rules: in space 1 and dont manage
yabai -m rule --add app="VMware Fusion" space=1_code manage=off
yabai -m rule --add app="Android" space=1_code manage=off
yabai -m rule --add app="qemu" space=1_code manage=off

# Window rules: in space 1
yabai -m rule --add app="^iTerm" manage=on space=1_code
yabai -m rule --add app="^WezTerm" manage=on space=1_code
yabai -m rule --add app=Burp space=1_code

# Window rules: in space 2
yabai -m rule --add app=Safari space=2_web
yabai -m rule --add app="Brave Browser" space=2_web

# Window rules: in space 3
yabai -m rule --add app="^KeePass" manage=on space=3_work
yabai -m rule --add app=Mail manage=on space=3_work
yabai -m rule --add app="Proton Mail" manage=on space=3_work
yabai -m rule --add app="Signal" manage=on space=3_work
yabai -m rule --add app="ProtonVPN" manage=on space=3_work
yabai -m rule --add app=Slack space=3_work
yabai -m rule --add app="Obsidian" space=3_work

# Window rules: in space 4
yabai -m rule --add app=Discord space=4_misc manage=on
yabai -m rule --add app=Spotify manage=on space=4_misc
yabai -m rule --add app=Firefox space=4_misc

# App specific rules
# I put them at the end so they canluajit override the window rules

# I dot not manage the opacity for obsidian because i want to set my own transparency for the app
# Recommended is dark "Border" theme with Apparence -> Transparancy off
yabai -m rule --add app="Obsidian" opacity=off

yabai -m rule --apply

# Window rule: general rules
yabai -m config window_border off
yabai -m config mouse_follows_focus on
yabai -m config normal_window_border_color 0x00FFFFFF
yabai -m config active_window_border_color 0x50ff8a65

yabai -m space --focus 1_code

echo "yabai configuration loaded.."

