#!/usr/bin/env zsh
# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# bsp or float (default: bsp)
yabai -m config layout bsp


# Set all padding and gaps to 20pt (default: 0)
yabai -m config top_padding    5
yabai -m config bottom_padding 5
yabai -m config left_padding   5
yabai -m config right_padding  5
yabai -m config window_gap     5


# set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier fn

# set modifier + left-click drag to resize window (default: move)
yabai -m config mouse_action1 move

# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize

# set focus follows mouse mode (default: off, options: off, autoraise, autofocus)
yabai -m config focus_follows_mouse autofocus

# floating windows are always on top (default: off)
#yabai -m config window_topmost off

# window opacity (default: off)
# example: render all unfocused windows with 90% opacity
yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.95

# Desktop labels
yabai -m space 1 --label web
yabai -m space 2 --label code
yabai -m space 3 --label music
yabai -m space 4 --label slack
yabai -m space 5 --label misc

# Move spaces to correct displays
yabai -m space web --display 1
yabai -m space code --display 2
yabai -m space music --display 1
yabai -m space slack --display 1
yabai -m space misc --display 2

# Window rules 
yabai -m rule --add app="^iTerm2" manage=on opacity=0.95 space=code
yabai -m rule --add app="^Préférences Système$" manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Mail" manage=off
yabai -m rule --add app="^Musique" manage=off space=music
yabai -m rule --add app=Safari space=web
yabai -m rule --add app="^Slack" space=slack

yabai -m config window_border on
yabai -m config mouse_follows_focus on
yabai -m config normal_window_border_color 0x00FFFFFF
yabai -m config active_window_border_color 0x50ff8a65

# Create two Safari instances and move the last one to misc space
if ! ps aux | grep "[/]Applications/Safari.app/Contents/MacOS/Safari" > /dev/null
then
open -a Safari 
sleep 4
fi
open -a iTerm
index="$(yabai -m query --windows | jq 'map(select(."app" == "Safari"))[1].id')"
yabai -m window $index --space misc
yabai -m space --focus web
yabai -m space --focus code

echo "yabai configuration loaded.."

