#!/usr/bin/env sh

spacebar -m config position top
spacebar -m config title on 
spacebar -m config spaces off
spacebar -m config power on

spacebar -m config spacing_left         20
spacebar -m config spacing_right        15

spacebar -m config right_shell on
spacebar -m config right_shell_command ~/.config/spacebar/notes

spacebar -m config icon_font "MesloLGS NF:Mono:13.0"
spacebar -m config icon_font "Font Awesome 5 Free:Solid:12.0"

spacebar -m config background_color  0xf0202020
spacebar -m config foreground_color  0xf0a8a8a8
spacebar -m config power_icon_color     0xffcd950c
spacebar -m config battery_icon_color   0xffd75f5f
spacebar -m config dnd_icon_color       0xffa8a8a8
spacebar -m config clock_icon_color     0xffa8a8a8

spacebar -m config clock_format "%d/%m/%y %R"

spacebar -m config clock_icon           
spacebar -m config dnd_icon             
spacebar -m config power_icon_strip      
spacebar -m config right_shell_icon 
